export class Fdcustomer{
    constructor(
        fdcid:number,
        firstname:string,
        lastname:string,
        address:string,
        dob:string,
        pan:string,
        gender:string,
        kyc:string,
        email:string,
        date:string,
        month:string,
        year:string,
        phone:string,
        joinapplicant:string,
        principal:number,
        period:number,
        nominee:string,
        rate:number,
        payout:string,
        amountavailable:number,
        amountwithdrawn:number,
        amountwithdrawndate:string,
        balance:number,
        status:string
        ){}
    }
